urban_project/board/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
# from .views import UpdateProfileStats

app_name = 'board'
urlpatterns = [
    path('', views.advertisement_list, name='advertisement_list'),
    path('advertisement/<int:pk>/', views.advertisement_detail, name='advertisement_detail'),
    path('add/', views.add_advertisement, name='add_advertisement'),
    path('edit/<int:pk>/', views.edit_advertisement, name='edit_advertisement'),
    path('delete/<int:pk>/', views.delete_advertisement, name='delete_advertisement'),
    path('likes/<int:pk>/', views.likes, name='likes'),
    path('dislikes/<int:pk>/', views.dislikes, name='dislikes'),
    path('', views.index, name='index'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urban_project/urban_project/urls.py
from django.contrib import admin
from django.urls import path, include
from board import views as board_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('board/', include('board.urls', namespace='board')),
    path('accounts/logout/', board_views.logout_view, name='logout'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', board_views.home, name='home'),
    path('signup/', board_views.signup, name='signup'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urban_project/board/models.py
from django.db import models
from django.contrib.auth.models import User


class Advertisement(models.Model):
    """
    Этот класс определяет модель для хранения информации об объявлениях в базе данных.
    """
    title = models.CharField(max_length=255)
    content = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to='advertisements/', blank=True, null=True)
    likes = models.IntegerField(default=0, verbose_name='Лайки')
    dislikes = models.IntegerField(default=0, verbose_name='Дизлайки')

    def __str__(self):
        """
        Метод используется для определения строкового представления объекта модели
        :return:
        """
        return self.title

class Comment(models.Model):
    """
    Этот класс определяет модель для хранения комментариев к статьям или другим объектам в базе данных.
    """
    advertisement = models.ForeignKey(Advertisement, related_name='comments', on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to='advertisements/', blank=True, null=True)

    def __str__(self):
        """
        Метод используется для определения строкового представления объекта модели
        :return:
        """
        return f'Comment by {self.author} on {self.advertisement}'

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    # Статистика
    total_visits = models.IntegerField(default=0)
    last_visit = models.DateTimeField(auto_now=True, editable=True)

    def __str__(self):
        return f'Profile for {self.user}'

urban_project/board/forms.py
from django import forms
from rest_framework import serializers

from .models import Advertisement, Profile
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User



class AdvertisementForm(forms.ModelForm):
    """
    Этот блок кода определяет метаданные (Meta) для модели Advertisement. model = Advertisement: Это указывает Django,
    что эти метаданные относятся к модели Advertisement. Это не обязательно нужно явно указывать, так как Django обычно
    может определить это автоматически.
    fields = ['title', 'content', 'author'] Это список полей модели, которые будут отображаться в форме модели. В
    данном случае это заголовок объявления (title), содержание (content) и автор (author).
    """
    class Meta:
        model = Advertisement
        fields = ['title', 'content', 'image', 'author', 'likes', 'dislikes']

class SignUpForm(UserCreationForm):
    """
    Этот класс SignUpForm представляет собой кастомную форму регистрации пользователя, которая расширяет стандартную
    форму UserCreationForm. UserCreationForm - Это стандартная форма Django для регистрации новых пользователей.
    SignUpForm расширяет UserCreationForm, что позволяет переопределить некоторые аспекты формы, если необходимо.
    Использование Meta позволяет задать метаданные формы без необходимости создавать отдельный экземпляр класса.
    Поле fields определяет, какие поля формы будут отображаться. В данном случае это базовые поля для регистрации
    пользователя.
    """
    class Meta:
        model = User
        fields = ('username', 'password1', 'password2',)

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')

class ProfileForm(serializers.ModelSerializer):
    class Meta:
        model = Profile
        fields = ('user', 'total_visits', 'last_visit')
    exclude = ['last_visit']

urban_project/board/views.py
from datetime import timezone
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from .models import Advertisement
from .forms import AdvertisementForm, UserForm, ProfileForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.shortcuts import render, redirect
from .forms import SignUpForm
from django.contrib.auth import login, authenticate
from .models import Profile
from django.shortcuts import render
from django.core.paginator import Paginator



def logout_view(request):
    """
    Этот метод выполняет выход пользователя из системы и перенаправляет его на домашнюю страницу.
    """
    logout(request)
    return redirect('home')

def signup(request):
    """
    Вызывает страницу для подписи объявлений.
    """
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('/board')
    else:
        form = SignUpForm()

    return render(request, 'signup.html', {'form': form})

def home(request):
    """
    Вызывает страницу home.html.
    """
    return render(request, 'home.html')

def advertisement_list(request):
    """
    Вызывает страницу advertisement_list.html.
    """
    posts = Advertisement.objects.all().order_by('-created_at')
    paginator = Paginator(posts, 3)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'board/advertisement_list.html', {'page_obj': page_obj})

def advertisement_detail(request, pk):
    """
    Вызывает страницу advertisement_detail.html.
    """
    advertisement = Advertisement.objects.get(pk=pk)
    return render(request, 'board/advertisement_detail.html', {'advertisement': advertisement})

@login_required  # Проверяет регистрацию пользователя
def add_advertisement(request):
    """
    Этот метод считывает данные объектов из класса Advertisement, проверяет были ли запрос "POST", обрабатывает
    данные формы, если все поля заполнены полностью, корректны и содержат все необходимые данные. Затем, при
    обавлении данных, автоматически устанавливает автора как текущего авторизованного пользователя. Если запроса "POST"
    не было, то возвращаемся к предыдущей странице без изменений.
    """
    if request.method == "POST":
        form = AdvertisementForm(request.POST)
        if form.is_valid():
            advertisement = form.save(commit=False)
            advertisement.author = request.user
            advertisement.save()
            return redirect('board:advertisement_list')
    else:
        form = AdvertisementForm()
    return render(request, 'board/add_advertisement.html', {'form': form})

@login_required    # Проверяет регистрацию пользователя
def edit_advertisement(request, pk):
    """
    Этот метод считывает данные объектов из класса Advertisement, проверяет были ли запрос "POST", обрабатывает
    данные формы, если все поля заполнены полностью, корректны и содержат все необходимые данные. Затем, при
    редактировании, автоматически устанавливает автора как текущего авторизованного пользователя. Если запроса "POST"
    не было, то возвращаемся к предыдущей странице без изменений.
    :param request:
    :param pk:
    :return:
    """
    advertisement = Advertisement.objects.get(pk=pk)
    if request.method == "POST":
        form = AdvertisementForm(request.POST, request.FILES, instance=advertisement)
        if form.is_valid():
            form.instance.author = request.user
            form.save()
            img_obj = form.instance
            # Перенаправляет на страницу с сохраненными исправлениями.
            return redirect('board:advertisement_detail', pk=img_obj.pk)
    else:
        # вызов функции которая отобразит в браузере указанный шаблон с данными формы и объявления.
        form = AdvertisementForm(instance=advertisement)
    return render(request, 'board/edit_advertisement.html',
                  {'form': form, 'advertisement': advertisement})

@login_required
def delete_advertisement(request, pk):
    """
    Этот метод считывает данные объектов из класса Advertisement, проверяет были ли запрос "POST", после чего удаляет
    объявление и возвращается в окно объявления.
    :param request:
    :param pk:
    :return:
    """
    advertisement = Advertisement.objects.get(pk=pk)
    if request.method == "POST":
        advertisement.delete()
        return redirect('board:advertisement_list')
    else:
        None
    return render(request, 'board/delete_advertisement.html', {'advertisement': advertisement})

@login_required
def create_advertisement(request):
    if request.method == "POST":
        form = AdvertisementForm(request.POST, request.FILES)
        if form.is_valid():
            advertisement = form.save()
            return redirect('board:advertisement_detail', pk=advertisement.pk)
    else:
        form = AdvertisementForm()
    return render(request, 'board/create_advertisement.html', {'form': form})

@login_required
def likes(request, pk):
    advertisement = Advertisement.objects.get(pk=pk)
    if request.method == "POST":
        advertisement.likes += 1
        advertisement.save()
        return redirect('board:advertisement_list')
    else:
        form = AdvertisementForm()
    return render(request, 'board/advertisement_list.html', {'advertisement': advertisement})

@login_required
def dislikes(request, pk):
    advertisement = Advertisement.objects.get(pk=pk)
    if request.method == "POST":
        advertisement.dislikes += 1
        advertisement.save()
        return redirect('board:advertisement_list')
    else:
        None
    return render(request, 'board/advertisement_list.html', {'advertisement': advertisement})


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    """
    Этот метод определяет количество входов каждого пользователя и сохраняет в базе данных
    :param sender:
    :param instance:
    :param kwargs:
    :return:
    """
    instance.profile.total_visits += 1
    instance.profile.save()

@login_required
def index(request):
    posts = Advertisement.objects.all().order_by('-created_at')
    paginator = Paginator(posts, 3)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'board/advertisement_list.html', {'page_obj': page_obj})

urban_project/board/templates/board/add_advertisement.html
{% extends 'base.html' %}

{% block content %}
<h2>Редактирование объявления</h2>
<form method="post"  enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Сохранить изменения</button>
</form>
{% if advertisement.image %}
    <img src=" {{ advertisement.image.url }}" alt="{{ advertisement.title }}" style="max-width: 100%; height: auto;">
{% endif %}
{% endblock %}

urban_project/board/templates/board/advertisement_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h1>{{ advertisement.title }}</h1>
<p>{{ advertisement.content }}</p>
{% if advertisement.image %}
    <img src=" {{ advertisement.image.url }}" alt="{{ advertisement.title }}" style="max-width: 100%; height: auto;">
{% endif %}

<div style="display:flex; flex-direction:column">
    <span>
        <a href="{% url 'board:edit_advertisement' advertisement.pk %}">Редактировать</a>
    </span>
    <span>
        <a href="{% url 'board:delete_advertisement' advertisement.pk %}">Удалить</a>
    </span>
</div>


<h2>
    <li>Имя автора объявления: {{ advertisement.author }}</li>
    <li>Количество входов: {{ advertisement.author.profile.total_visits }}</li>
    <li>Последний визит: {{ advertisement.author.profile.last_visit }}</li>
    <li>Всего загружено объявлений: {{ advertisement.author.profile.id }}</li>
</h2>
{% endblock %}

urban_project/board/templates/board/advertisement_list.html
{% extends 'base.html' %}

{% block content %}
<h1>Рекламные объявления</h1>

{% if user.is_authenticated %}
    <a href="{% url 'board:add_advertisement' %}"><button>Добавить объявление</button></a>
{% endif %}

<body>
<div class="row">
    {% for post in page_obj %}
        <h3>Автор: {{ post.author.username }}</h3>
        <form action="{% url 'board:likes' pk=post.pk %}" method="post">
            {% csrf_token %}
            <button type="submit">👍 {{ post.likes }}</button>
        </form>
        <form action="{% url 'board:dislikes' pk=post.pk %}" method="post">
            {% csrf_token %}
            <button type="submit">👎 {{ post.dislikes }}</button>
        </form>

        <li>
          <a href="{% url 'board:advertisement_detail' pk=post.pk %}">{{ post.title }}</a>
          {% if post.image %}
            <img src=" {{ post.image.url }}" alt="{{ post.title }}" style="max-width: 100%; height: auto;">
          {% endif %}
        </li>
    {% endfor %}
</div>
<h2>
       {% if page_obj.has_other_pages %}
    <nav aria-label="Page navigation">
        <ul class="pagination-string">
            {% if page_obj.has_previous %}

                <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                   <span aria-hidden="true">≪≪≪</span>
                </a>

            {% else %}

                <a class="page link" href="#" aria-label="Previous">
                    <span aria-hidden="true">≪≪≪</span>
                </a>

            {% endif %}

            {% for i in page_obj.paginator.page_range %}
                {% if page_obj.number == i %}

                    <a class="page-link" href="#">{{ i }}</a>

                {% else %}

                    <a class="page-link" href="?page={{ i }}">{{ i }}</a>

                {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}

                <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                    <span aria-hidden="true">≫≫≫</span>
                </a>

            {% else %}

                <a class="page-link" href="#" aria-label="Next">
                    <span aria-hidden="true">≫≫≫</span>
                </a>

            {% endif %}
        </ul>
    </nav>
{% endif %}
</h2>
<h2>
    <li>Имя текущего автора: {{ user.username }}</li>
    <li>Количество входов: {{ user.profile.total_visits }}</li>
    <li>Последний визит: {{ user.profile.last_visit }}</li>
    <li>Всего загружено объявлений: {{ user.profile.id }}</li>
</h2>

</body>
{% endblock %}

urban_project/board/templates/board/create_advertisement.html
{% extends 'base.html' %}

{% block content %}
  <h2>Add Advertisement</h2>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
  </form>
<!-- profile.html -->

<form method="post">
  {% csrf_token %}
  {{ user_form.as_p }}
  {{ profile_form.as_p }}
  <button type="submit">Сохранить изменения</button>
</form>
{% endblock %}

urban_project/board/templates/board/delete_advertisement.html
{% extends "base.html" %}

{% block title %}Удаление объявления{% endblock %}

{% block content %}
<h1>Удалить: "{{ advertisement.title }}"</h1>
<h2>И его содержание: "{{ advertisement.content }}"</h2>
<div class="module">
    <form action="" method="post">
        {% csrf_token %}
        <p>Удаляем? Точно?! После удаления это объявление не восстановить!!!</p>
        <button type="submit">Удалить</button>
    </form>
</div>
{% endblock %}

urban_project/board/templates/board/edit_advertisement.html
{% extends 'base.html' %}

{% block content %}
<h2>Редактирование объявления</h2>
<form method="post"  enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Сохранить изменения</button>
</form>
{% if advertisement.image %}
    <img src=" {{ advertisement.image.url }}" alt="{{ advertisement.title }}" style="max-width: 100%; height: auto;">
{% endif %}
{% endblock %}

urban_project/board/templates/board/index.html
<!DOCTYPE html>
<html lang="en">
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
   {{ form.as_p }}
  <button type="submit">Upload</button>
</form>

{% if img_obj %}
  <h3>Succesfully uploaded : {{img_obj.title}}</h3>
  <img src="{{ img_obj.image.url}}" alt="connect" style="max-height:300px">
{% endif %}